component: aws-lambda 
name: create-book

inputs:
  src: ./
  name: ${name}-${stage}
  description: Create a book in the book table
  memory: 512
  env:
    TABLE_NAME: ${output:books-table.name}
  roleName: ${output:book-table-iam.name}