service: serverlessguru-code-challenge-backend
app: serverlessguru-code-challenge
org: gastonmichel
variablesResolutionMode: 20210326
custom:
  tableName: 'books-table-${self:provider.stage}'

provider:
  name: aws
  stage: dev


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.tableName}
        TableName: ${self:custom.tableName}