app: serverlessguru-code-challenge
org: gastonmichel
name: appsync-api
component: graphql
service: serverlessguru-code-challenge-api

variablesResolutionMode: 20210326

provider:
  name: aws

inputs:
  src: ./
  resolvers:
    Query:
      getBookById:                      
        lambda: getBookById
        request: request.vtl
        response: response.vtl
      listBooks:
        lambda: listBooks
        request: request.vtl
        response: response.vtl
    Mutation:
      createBook:
        lambda: createBook
        request: request.vtl
        response: response.vtl
      deleteBook:
        lambda: deleteBook
        request: request.vtl
        response: response.vtl
      updateBook:
        lambda: updateBook
        request: request.vtl
        response: response.vtl
