component: aws-lambda 
name: get-book

inputs:
  src: ./src
  name: ${name}-${stage}
  description: Get a book from the book table
  memory: 512
  env:
    TABLE_NAME: ${output:books-table.name}
  roleName: ${output:book-table-iam-read.name}