component: aws-lambda 
name: update-book

inputs:
  src: ./
  name: ${name}-${stage}
  description: Update a books in the book table
  memory: 512
  env:
    TABLE_NAME: ${output:books-table.name}
  roleName: ${output:book-table-iam-write.name}