app: serverlessguru-code-challenge
org: gastonmichel
service: serverlessguru-code-challenge-backend
# variablesResolutionMode: 20210326

custom:
  tableName: 'books-table-${sls:stage}'

provider:
  name: aws
  runtime: python3.9
  memorySize: 512
  lambdaHashingVersion: 20201221
  environment:
    TABLE_NAME: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ BookTable, Arn ]

functions:
  getBookById:
    handler: lambda.getBookById
    name: getBookById
  listBooks:
    handler: lambda.listBooks
    name: listBooks
    memorySize: 1024
  createBook:
    handler: lambda.createBook
    name: createBook
  deleteBook:
    handler: lambda.deleteBook
    name: deleteBook
  updateBook:
    handler: lambda.updateBook
    name: updateBook

resources:
  Resources:
    BookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}