service: serverlessguru-code-challenge-backend
app: serverlessguru-code-challenge
org: gastonmichel
variablesResolutionMode: 20210326

provider:
  name: aws
  stage: dev
  runtime: python3.9
  memorySize: 512
  lambdaHashingVersion: 20201221

functions:
  getBookById:
    handler: lambda.getBookById
    name: getBookById
  listBooks:
    handler: lambda.listBooks
    name: listBooks
    memorySize: 1024
  createBook:
    handler: lambda.createBook
    name: createBook
  deleteBook:
    handler: lambda.deleteBook
    name: deleteBook
  updateBook:
    handler: lambda.updateBook
    name: updateBook

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        TableName: 'books-table-dev'