component: aws-lambda 
name: list-books

inputs:
  src: ./
  name: ${name}-${stage}
  description: List books from the book table
  memory: 512
  env:
    TABLE_NAME: ${output:books-table.name}
  roleName: ${output:book-table-iam.name}