component: graphql
name: books-api

inputs:
  name: ${name}-${stage}
  src: ./
  domain: ${stage}.gastonmichel.com.ar
  resolvers:
    Query:
      getBookById:                      
        lambda: ${output:get-book.name}
        request: request.vtl
        response: response.vtl
      listBooks:
        lambda: ${output:list-books.name}
        request: request.vtl
        response: response.vtl
    Mutation:
      createBook:
        lambda: ${output:create-book.name}
        request: request.vtl
        response: response.vtl
      deleteBook:
        lambda: ${output:delete-book.name}
        request: request.vtl
        response: response.vtl
      updateBook:
        lambda: ${output:update-book.name}
        request: request.vtl
        response: response.vtl
