name: Serverless Deploy Stage

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-component:
    name: deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    strategy:
      matrix:
        component: [lambda-backend,appsync-api,react-front-end]
    steps:
    - name: Set Stage from Branch
      id: vars
      run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}
    - name: Checkout
      uses: actions/checkout@v2
    - name: serverless deploy --stage ${{ steps.vars.outputs.stage }}
      uses: serverless/github-action@master
      run: serverless deploy --stage ${{ steps.vars.outputs.stage }}
      working-directory: ${{ matrix.component }}