name: Deploy master branch

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    strategy:
      matrix:
        component: [lambda-backend,appsync-api,react-front-end]
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: 14.x
    # - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --config ${{ matrix.component }}/serverless.yaml --stage ${{ github.ref }}