name: Serverless Deploy Stage

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-serverless-components:
    name: deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
    - name: Set Stage from Branch
      id: vars
      run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}
    - name: Checkout
      uses: actions/checkout@v2
    - name: serverless deploy --stage ${{ steps.vars.outputs.stage }}
      uses: serverless/github-action@master
      with:
        args: serverless deploy --stage ${{ steps.vars.outputs.stage }}